"""Change progress field to JSON

Revision ID: bba7da09b1f2
Revises: c72dad935055
Create Date: 2025-09-02 09:13:31.948315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bba7da09b1f2'
down_revision = 'c72dad935055'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE game_sessions ALTER COLUMN progress TYPE JSON USING progress::json")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_sessions', 'progress',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
